feat: support autosize fit for faceted plots
vega/vega-lite pull request #6672
Opened 2020-06-22 22:00 UTC by drgould

Based on discussion in #5219 and stealing some code from #5225, this adds support for specifying the outer plot dimensions and sizing the inner facets automatically. This also unlocks `autosize: fit(-x/-y)`.

Note: this is only for specs which explicitly define the facet operator at the top level.

- [ ] Add tests
- [ ] Update docs

2020-08-12 20:38 UTC, domoritz commented
This is exciting. @drgould let us know when this is ready for a review.

I know @willium was interested in this feature as well.

2020-11-19 10:00 UTC, willium commented
Very excited for this!

2020-11-19 18:40 UTC, domoritz commented
Hi @drgould, do you plan to finish this pull request?

2020-11-19 19:04 UTC, drgould commented
Sorry, yeah I haven't had a chance to get back to this. My team has been hard at work implementing vega-lite into our product and this kinda fell on the back burner. We just launched it on Tues. so now were starting to pick back up some of this tech debt. The version we're currently using is a bit behind and we've been in need some of the new features so this will likely be prioritized very soon.

2020-11-19 19:14 UTC, domoritz commented
Oh, that's awesome to hear. Congrats on launching the feature. If you want, you can send a pull request to add it to https://vega.github.io/vega-lite/ecosystem.html.

More generally, I would be happy to collaborate more closely on features and make sure to do a quick review/release turn around when you need a particular feature for your product. You have probably seen [our roadmap](https://github.com/vega/roadmap/projects/1) and if there are bigger things you would like to tackle, we can add it there as well.

2021-02-25 10:17 UTC, wmarques commented
Hi @domoritz @drgould  !
We would really need this feature as we are developing customisable widget dashboards using vega-lite. 
So having responsive grouped bar charts is mandatory for us and I think it's impossible without this ticket.

Do you need any help to merge this ? I'd be glad to help on that in order to have this into vega-lite :)

2021-02-25 10:26 UTC, domoritz commented
@wmarques yes, I won't have the cycles to implement this but I can review a pull request. Could you open a new pull request with this code and any improvements you want to make?

2021-02-25 10:30 UTC, wmarques commented
@domoritz Sure, i'll check if this code works for us first, thanks for the quick answer !

2021-02-25 10:34 UTC, domoritz commented
Thank you for offering to help. I look forward to your contributions.

2021-02-25 19:25 UTC, drgould commented
@wmarques If all you need is a "responsive" grouped bar it's fairly easy to accomplish without faceting using a few transforms and a labelExpr: https://vega.github.io/editor/#/gist/2d591c1cea91c8281e27900240f058b8/grouped_bar_single_layer.json

As for finishing up this PR, it's finally in my tasks for this sprint so I should be finishing it up very soon.

2021-02-26 09:23 UTC, wmarques commented
@drgould Oh thanks alot I'll look into your example !
And that's great news for this ticket :) 
Thank you both for your very fast help !

2021-03-14 03:52 UTC, domoritz commented
Just wanted to check in to see whether you need any help with getting this over the finish line. Please mark the pull request as ready for review when you want me to look at it.

2021-03-15 16:51 UTC, drgould commented
Ok I think I have this in a good enough place to open this up for review. I need a bit of guidance about any additional unit/spec/visual tests that might help as well as the changes to the docs.

2021-03-30 19:57 UTC, domoritz commented
The example generation depends on specifics of the OS so we usually let the ci do it (see contributing docs). If the ci doesn't do it for you, can you check your setup in your fork? I can help if there is some issue with it.

2021-03-31 16:57 UTC, drgould commented
Yeah there definitely seems to be an issue with how the fork is set up. The really weird thing is it was working when I originally created this PR and didn't touch any of the workflows/etc. so ¯\_(ツ)_/¯

The only thing I see that's obviously wrong is the check workflow can't commit likely because the actions bot key is meant for this repo rather than the fork. But regardless the examples still aren't building correctly.

2021-03-31 17:03 UTC, domoritz commented
Can you try setting a `GH_PAT` in your repo secrets of your fork? If it doesn't work, I can copy your branch into this repo when you think it's ready. 

You can definitely build the schema locally, though (using `yarn schema`).

2021-04-04 18:27 UTC, domoritz commented
I copied the pull request to our repo over at https://github.com/vega/vega-lite/pull/7356 so we can build the examples.

2021-04-08 04:15 UTC, domoritz requested changes
This is great and pretty close to being done! I also just finished a deadline so I have more time to do faster reviews. If you can address the issues I found, I think we can merge this soon.

Here are a few problems I found. 

## Specs with row/column and autosize do not work. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "width": 500,
  "height": 500,
  "autosize": {
    "type": "fit"
  },
  "data": {"url": "data/barley.json"},
  "mark": "bar",
  "encoding": {
    "column": {"field": "year"},
    "x": {"field": "yield", "type": "quantitative", "aggregate": "sum"},
    "y": {"field": "variety", "type": "nominal"},
    "color": {"field": "site", "type": "nominal"}
  }
}
```

Note that this spec also generates a warning "Autosize "fit" only works for single views and layered views.", which is not correct anymore since we do support fit for faceted plots as well. 

This should be a simple fix in the normalized where we should generate. 

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "autosize": {"type": "fit"},
  "width": 500,
  "height": 500,
  "padding": 0,
  "data": {"url": "data/barley.json"},
  "facet": {"column": {"field": "year"}},
  "spec": {
    "mark": "bar",
    "encoding": {
      "x": {"field": "yield", "type": "quantitative", "aggregate": "sum"},
      "y": {"field": "variety", "type": "nominal"},
      "color": {"field": "site", "type": "nominal"}
    }
  }
}
```

## Adding autosize to x in this chart with wrapped facet breaks it

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "name": "trellis_barley",
  "width": 500,
  "autosize": {
    "type": "fit-x"
  },
  "padding": 0,
  "data": {"url": "data/barley.json"},
  "columns": 2,
  "facet": {
    "field": "site",
    "type": "ordinal",
    "sort": {"op": "median", "field": "yield"}
  },
  "spec": {
    "height": {"step": 12},
    "mark": "point",
    "encoding": {
      "x": {
        "aggregate": "median",
        "field": "yield",
        "type": "quantitative",
        "scale": {"zero": false}
      },
      "y": {"field": "variety", "type": "ordinal", "sort": "-x"},
      "color": {"field": "year", "type": "nominal"}
    }
  }
}
```

![image](https://user-images.githubusercontent.com/589034/113967484-ee860e80-97e5-11eb-810e-2b4fc5b3b536.png)

2021-04-13 15:23 UTC, domoritz commented
@drgould is there anything I can help with to get this pull request over the finish line?

2021-04-13 23:50 UTC, drgould commented
Sorry been working on some other things and haven't had a chance to get back to this. I'll hopefully have some time to make those changes soon.

2021-04-15 09:02 UTC, cdomergue commented
Hello.

Doest the pyramidal distribution (ie: using hconcat) will be affected by this feature and became responsive ?

Thank you.

Code: [Vega editor](https://vega.github.io/editor/#/url/vega-lite/N4Igbglgpg7iBcoDOAXATgewNZQQOwFcAbIgXwBoQALAYwzxoEMUEBtUdRvJAMwzQC2bUDwhEUUNAhHQiAEwQgkdNFAAqATwAOuSlACOBRkUVQ6AZRW5SpALqUUEFEVyIQEgB4t4IMxkv8uiB0RPyKAMQAjADMAJwALACsACIglFw0VGE+qIxoLBTUUBAA5lTewfQojBB4kmkgAnlYigBGeQ1QDBhytSXSIBoDolDyinJmYkGMHhBI+MRElEj8FRPKXb14-YUeA4wlJaolzK5KBEKUI2M+dAR4LA5OLgsk6bPzbnyCzIrzTzQsABhDD3bzRQorfLjKAbPBbHaUELZGSjBQ5KyaHQNZTGVygNBcEquVggKJxJKpSjhaIAJgA7ABBABC9JAtkKLmJ8NeZBs5FAkFgA1QmBwvMKTTQLTcKG0Z08jxAxlKeEUNC6EikhSoxTKFToDxqdSkem6CIGQy+snRIAmNCmDTl2J8-C2xgaMzmvOWqxhcIthUVwxtMIdLwc8sUhi4jmqjjA1n5HEJ3G+Qng7BAonE9WtaL+mKjehjJhyjB4UDlAVUIBs9iKpXK6qqxvqT2c+PcUC8fwrVY0NaCyKkPhpDJZbPSDCyo98PMlzTaHTNdAtbitqJudsmEfcz1chDeyo+PqUfp86w18L6dcoezcByOUBOEj+Fwa11tdweToPZ69T4RH4JoKn+fdARBMEEAhQoRxDAsMUCLEgi5TYJXrBxU14EDhGzDAblJPwhxxftqysdl0k+UllGQ4tKmgjkG0NUR+jcGgCFQDABAAMRA5gUM+dACCgK4qkUZkADkAAVpIaNCeTcIhGFaUYQVCOdwkSIFtO0hp+GgX8fFaDAUBQbiGhCC5uAGHstDnHhQn4AAKGAIDkFAqAAekiAAGXyAEo7xAZSNFBbxQBMsyLMfGdskady5BeGx+RANyPKoFsjVqdtG31LLqhy00QHaQEjlBRSjyWO1mEYAYwGMETqNAe1HXgPy9AsCj4AANmWMjB262IKBa3dXFpXzOv8bqOqUAaSPagAOEad3DVxokm3wusCBBInpfrK3Inb2p6lbWpeeB4k24juomg6BwW2lIjOsaEESa7ttreBonie6jq+6JnoFVa2p6j7puOuI-sGyHEhetaEHpcGFo26GUd8+G2sW5HbsWtHbvpTGLtiHHjsiPG5sOmGvomonXD80mvr2-GyeejlSCAA)

2021-04-15 14:33 UTC, domoritz commented
No, this is for faceted charts only. We already support single view and layered plots.

2021-04-19 04:40 UTC, kanitw requested changes
Thanks so much for submitting the PR!  It's not very common that people digged deep into the codebase to submit enhancement, so we really appreciate that. I think this would be an awesome addition for Vega-Lite. 

To add to @domoritz's point, this PR currently only have one example, which might not cover different cases we want to support.  

To make sure that we have tested (and have regression tests) for different cases, could you please include more examples, showing combinations of the following variations?

- Width/Height -- currently in the only example provided, we see that width and height are only outside.  However, it would be great to have examples that test when there is a width at the facet level, but the height is based on the unit spec's height.

- Facet -- In the only example provided, the example is a facet column.  And you include facet row, facet row x column, and wrapped facet? 

If some of these cases do not work, please instead add warning messages by using log.warn() from `src/log` and add new log messages to `src/log/messages`.

2021-04-19 04:40 UTC, kanitw commented on site/docs/view/size.md
> +The width and height of multi-view displays including [concatenated](concat.html), [faceted](facet.html), and [repeated](repeat.html) are generally determined based on the size of the composed unit a
> generally

"by default"?

2021-05-26 21:56 UTC, drgould commented
Our priorities shifted quite significantly a couple months ago and I haven't had any time to get back to this. I was hoping I would be able to carve out some time to finish this up but realistically I won't be able to do any work on this for at least 3 months. At this point it might be better if someone else takes this over.

2021-05-26 22:02 UTC, domoritz commented
Thanks for the update and good luck with the new direction @drgould. 

@wmarques do you have time to take it from here?

2021-08-14 16:27 UTC, smashmirrorcardboardface commented
is this likely to get released soon?  its exactly what i need

2021-08-14 21:21 UTC, domoritz commented
Since it's not merged, no. Please help us push it over the finish line if you need it.

2022-01-06 09:50 UTC, fgenoese commented
Interested in this one as well.

2023-09-27 20:59 UTC, BradyJ27 commented
> Since it's not merged, no. Please help us push it over the finish line if you need it.

Would you be able to summarize what is needed for this to be completed? I may have some time to look into it!

2023-09-29 12:48 UTC, domoritz commented
That's awesome. It's been a while so I can't summarize it but you should find everything in the comments in this pull request. Let us know if you have specific questions.

2025-01-29 14:57 UTC, nmerinos commented
Is there any chance of this getting merged soon or any alternative solutions/workarounds?

2025-01-29 15:02 UTC, domoritz commented
I'll close this since it's stalled (comments for what's left above). If someone wants to redo it, that would be awesome.

2025-01-29 15:02 UTC, closed without merging