Update ecosystem.md
vega/vega-lite pull request #7617
Opened 2021-07-26 14:29 UTC by qingchentju

add vega-lite-linter package and vizlinter editor

Please:

- [ ] Make the pull requests (PRs) atomic (fix one issue at a time). Multiple relevant issues that must be fixed together? Make atomic commits so we can easily review each issue.
- [ ] Provide a concise title as a [semantic commit message](https://www.conventionalcommits.org/) (e.g. "fix: correctly handle undefined properties") so we can easily copy it to the release note.
  - Use imperative mood and present tense.
- Mention relevant issues in the description (e.g., `Fixes #1` / `Fixes part of #1`).
- [ ] Lint and test (Run `yarn test`).
- [ ] If you send a pull request from a fork, make sure that GitHub actions run successfully. Make sure to add a [`GH_PAT` secret](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) for a [personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) with public repository permissions.
- [ ] Review your changes before sending the PR (to ensure code quality).
- For new features:
  - [ ] Add new unit tests.
  - [ ] Update the documentation under `site/docs/` + add examples.

Tips:

- https://medium.com/@greenberg/writing-pull-requests-your-coworkers-might-enjoy-reading-9d0307e93da3 is a nice article about writing a nice PR.
- Use draft PR for work in progress PRs / when you want early feedback (https://github.blog/2019-02-14-introducing-draft-pull-requests/).

2021-07-26 14:58 UTC, domoritz requested changes

2021-07-26 14:58 UTC, domoritz commented on site/ecosystem.md
> +- [VizLinter](https://vizlinter.idvxlab.com/), an online Vega-Lite editor with linting and fixing functions based on vega-lite-linter for Vega-Lite developers to create and validate visualizations.
```suggestion
- [VizLinter](https://vizlinter.idvxlab.com/), an online Vega-Lite editor with linting and fixing functions based on vega-lite-linter.
```

2021-07-26 14:58 UTC, domoritz commented on site/ecosystem.md
> +- [Vega-Lite-Linter](https://github.com/idvxlab/vega-lite-linter) is a python package to help users detect flaws and rectify already-built but defective visualizations.
```suggestion
- [Vega-Lite-Linter](https://github.com/idvxlab/vega-lite-linter) is a python package to help users detect and fix encoding issues. 
```

2021-08-02 02:34 UTC, qingchentju commented
Hi, Dominik! Thank you for the suggested changes. I wonder whether our new package can be marked as featured plugins or tools. 
Thanks again.

Best,
Qing

2021-07-26 22:58:16"Dominik Moritz" ***@***.***>写道：

@domoritz requested changes on this pull request.

In site/ecosystem.md:

> @@ -25,6 +25,7 @@ We mark featured plugins and tools with a <span class="octicon octicon-star"></s

 - [Codimd](https://github.com/hackmdio/codimd), realtime collaborative markdown notes editor with support of various diagram syntaxes including [Vega-Lite](https://hackmd.io/c/codimd-documentation/%2F%40codimd%2Fextra-supported-syntax#Vega-Lite).

 - [Ivy](http://ivy-vis.netlify.app/), an Integrated Visualization Editing environment that wraps Vega-Lite (among other declarative visualization grammars) as templates to facilitate reuse, exploration, and opportunistic creation. Includes an in-app reproduction of [Polestar](https://github.com/vega/polestar).

 - [Deneb](https://deneb-viz.github.io), a Power BI custom visual with an editor for Vega-Lite or Vega specifications.

+- [VizLinter](https://vizlinter.idvxlab.com/), an online Vega-Lite editor with linting and fixing functions based on vega-lite-linter for Vega-Lite developers to create and validate visualizations.


⬇️ Suggested change
-- [VizLinter](https://vizlinter.idvxlab.com/), an online Vega-Lite editor with linting and fixing functions based on vega-lite-linter for Vega-Lite developers to create and validate visualizations.

+- [VizLinter](https://vizlinter.idvxlab.com/), an online Vega-Lite editor with linting and fixing functions based on vega-lite-linter.



In site/ecosystem.md:

> @@ -55,6 +56,7 @@ We mark featured plugins and tools with a <span class="octicon octicon-star"></s

 - [Vega.rb](https://github.com/ankane/vega) brings Vega and Vega-Lite to Ruby.

 - [Jekyll Diagrams](https://github.com/zhustec/jekyll-diagrams) A Jekyll plugin with support for Vega & Vega-Lite and others diagramming libraries.

 - [Liquid Diagrams](https://github.com/zhustec/liquid-diagrams) A Liquid plugin with support for Vega & Vega-Lite and others diagramming libraries.

+- [Vega-Lite-Linter](https://github.com/idvxlab/vega-lite-linter) is a python package to help users detect flaws and rectify already-built but defective visualizations. 


⬇️ Suggested change
-- [Vega-Lite-Linter](https://github.com/idvxlab/vega-lite-linter) is a python package to help users detect flaws and rectify already-built but defective visualizations. 

+- [Vega-Lite-Linter](https://github.com/idvxlab/vega-lite-linter) is a python package to help users detect and fix encoding issues. 



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-08-02 17:42 UTC, domoritz commented
We mark things as featured once they are a bit more mature.

2021-08-02 19:06 UTC, merged