examples: interactive earthquakes
vega/vega-lite pull request #8138
Opened 2022-05-02 19:10 UTC by pared

Please:

- [x] Make the pull requests (PRs) atomic (fix one issue at a time). Multiple relevant issues that must be fixed together? Make atomic commits so we can easily review each issue.
- [x] Provide a concise title as a [semantic commit message](https://www.conventionalcommits.org/) (e.g. "fix: correctly handle undefined properties") so we can easily copy it to the release note.
  - Use imperative mood and present tense.
- Mention relevant issues in the description (e.g., `Fixes #1` / `Fixes part of #1`).
- [ ] Lint and test (Run `yarn test`).
- [x] If you send a pull request from a fork, make sure that GitHub actions run successfully. Make sure to add a [`GH_PAT` secret](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets) for a [personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) with public repository permissions.
- [x] Review your changes before sending the PR (to ensure code quality).
- For new features:
  - [ ] Add new unit tests.
  - [ ] Update the documentation under `site/docs/` + add examples.

Tips:

- https://medium.com/@greenberg/writing-pull-requests-your-coworkers-might-enjoy-reading-9d0307e93da3 is a nice article about writing a nice PR.
- Use draft PR for work in progress PRs / when you want early feedback (https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Related to #1486.
Reimplementing the [earthquakes example](https://vega.github.io/vega/examples/earthquakes/) in `vega-lite`. 
I did not find it in existing examples.
I would like to ask for some feedback, as I have a problem with scaling the `earthquakeSize`, I am unable to find an option that would allow me to control the `pointRadius` from the projection using the `magnitude` obtained from datapoints properties. I have been [playing around with standard `circle` mark](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemgDMABh1L4NMlm16lOAE5tJcKJnbzUoTAE8ccNCDYX6bMhaQcGBooRRArTCRMD1QAbVAII1kkQU8IqLgdEABfBQSklLS2SOiARhyFHQBdXJAcJACECDR4kGSEGPDijKylYhSGGNKzECYaWTU0UHGcBkw0pFkyDyUEcbR+UoAOfRBkAA80bd2IaJwj7NzQds70srD+wUG0XbGJqZAZuYWllb311CbHarJCHVDHJSnODncGXPJtJAdTxwBr0ACODCQAGs4ABlGgALz+j2eqAAbEo3pMnJ9ZLN5ugAr8wmtHLsDkcAEyQs4XbJVJSCJAuOAWFqgNRRFA0iBBUUxTAWQa1ZAWLEfVzuTzLNgQGCBP4AMxoglS6BSITgTCeHjhEqlHxunmU3kEkyUDAsZpAksiBBdXrUm2GCCkMnkSkN3mQDOcbk6mDYOGs4bChpRmE9nSgbAYskVNDgzThewa6ppms6Or1BrTJu9rMwUAsKIQYVOVhxnmtSCg6rtPodNKd6BRPhgGOxRbCnu9vqQBDH6MxOIgYbkaejUQ18c80g35is7h8Lk86aiWeLtUViwgUYsbbioCgKSgDCF0U8voYoZ1HUVLiUDm3hqOMGQQLE1RhEgzToIIci0Jmai2vCL6CG+H6dN+v5wGw-4WIBwEWKByTRBBpRVNBsEgB+dAMMhOQCqWao7lq6BQDQFhQIIfw5vBYqMnA7pePUHGuC8lAAJyQoSMSgHA+yWMiqITiueKyQAVBAaI+AAFNhlCWEmor2EWlDIGQACUOS1HAsg5iRZAfPBSx0QxNLGnAbqeC5iH0X8laeJO+Z0FENCkBUNFhUhckgJ53lwdF-lhIF6DBfYJThbalxMTmsjGk5TiXEAA) but in that case it seems that points have priority over earth projection making the image unclear. 

I would love some feedback how to progress with this one, as I could not find `vega-lite` example touching similar problem.

2022-05-02 19:13 UTC, pared commented
Sorry, I intended to make it draft PR, but did not do that in the end. Should close this one and open a new one?

2022-05-02 19:46 UTC, mattijn commented
Related: https://github.com/vega/vega-lite/issues/3396

`pointRadius` is not supported yet in VL.

If using `mark_circle` you'll need to filter the bubbles based `lat`/`lon`. For `rotate0` this is `(rotate0 * -1) - 90 < datum.lon && datum.lon < (rotate0 * -1) + 90`. 

See also observablehq variant (edit cell to see the VL) https://observablehq.com/@domoritz/earthquakes-in-vega-lite

And altair created-variant: https://deploy-preview-1--spontaneous-sorbet-49ed10.netlify.app/user_guide/marks/geoshape.html#expression

![image](https://user-images.githubusercontent.com/5186265/166077067-142dd09b-ba25-4630-81e5-42d62ab1f0a8.gif)

2022-05-03 22:15 UTC, domoritz commented
I converted it to a draft.

2022-05-23 21:42 UTC, pared commented
I spent some time trying to make the scale similar to the original vega plot. The results are in the current version of the branch.

2022-05-31 18:16 UTC, domoritz requested changes
Looks great otherwise.

2022-05-31 18:16 UTC, domoritz commented on examples/specs/interactive_geo_earthquakes.vl.json
> +  "config": {}
```suggestion
  ]
```

2022-05-31 18:16 UTC, domoritz commented on examples/specs/interactive_geo_earthquakes.vl.json
> +    "rotate": [{"signal": "rotate0"}, {"signal": "rotate1"}, 0]
```suggestion
    "rotate": {"expr": "[rotate0, rotate1, 0]"}
```

2022-05-31 20:55 UTC, merged

2022-06-01 10:42 UTC, pared commented
Thanks, @domoritz. if i want to contribute more, should I go for more examples or start looking at the issues?

2022-06-21 21:36 UTC, mattijn commented
side-note: I was wondering how you'd done the `rotate1` expression, since I couldn't get it to work in all edge-cases. I notice you run into the same issues as I did when I was experimenting with this (and therefor I did not include `rotate1`). 

Observe the west coast of north america in this animated gif: 

![ezgif com-gif-maker-5](https://user-images.githubusercontent.com/5186265/174900781-e0626850-4288-4390-8813-5582c755ae55.gif)
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAdxoATemgDMABh1L4NMlm16lOAE5tJcKJnbzUoTAE8ccNCDYX6bMhaQcGBooRRArTCRMDycQOAAPS08AbQiouH0AAjTogEYFTJ0AXRAAX1LzJACECDRk0FkkBBjwtkjonTDiJEEGGP0QJhpZNTRQYZwGTE8A2TIPJQRhtH4ATgHkeLR1pQhonDRc8oUGppacuFyunr60AaGRsZAJqZmkOYWQJcc1jaQt1A7EB7OAHVBHCqnZqeOBVegARwYSAA1nAAMo0ABen26vRiADYlA9RrEXtN0LN5mFvndFv9DgAmXb7O6UCFFJSCJAuOAWOqgNRRFCxCBBXkxTAWPoVL5VZFPVzuTzzNgQGCBT4AMxogkEnh6ITgTDxZUhIEFkSejWh6GU3kEoyUDAsevQFqQBDtLrU-FyuR0CCkMnkSk13mQ5OcbhamDYOGswbCmthmGdLSgbAYsklNDgtWOsos8tiipaKrVGqTOtdX2GmCgFlhCDCeysqM8xqQUHlxwFQqtZxhcJgiJRebCzpr7oIsJ8I6RqIgQbkSfDUQV0c80hX5is7h8Lk8yaiafzMsl7wgYYszdQ9RAUB6UAYXOingtDEDKuakpclAz3hqMM6QQMkxRhEgtToIIci0KmageGaj6CM+r4tB+X5wGwP4WH+AEWEBjTRKBuQlEokGeK+dAMAhZQnCA2qCNEfLoAAFBcOiZAAVJkvoAJS8Zk6yZAAPJkGGUDBczUQhmQAGRyeJJ6BlJcE0XAomZOxbTpJxPH8ZkADUQmcQpWkXLk3G8bkAn8CZmkSVR8EaWZjlRDJGlidp7SXFZBnGesdGgMhqHpO+ymUJYca8vYeaUMgZAQVBspkLIHllByhbFlGSroFANAWFAgifBmMEseEcCOl4OBdnQh6oDolAMmIMpwLIGaEYlsSqelsTanADqUbB6VKKWnijtmdDuaQdEgE56lPP1g3Qe5zlhGN6ATfY7Q0DNMoQFiMSgMV8yPKgsgvoIoa5stKVpWto2bptSKTTtM27MhR0gBtwLwj4YRqNhSDLHe+j+sUSiUjEYH0QkSToPGyisbOCILuih0FFofEZQWsZsExNBgveS0knd6WlEU5SU0AA)

Still a nice example though!

2022-06-22 20:57 UTC, pared commented
@mattijn I was playing around with it but I guess I did not get into this edge case. I should probably give it a little bit more though.

2022-08-23 15:46 UTC, pared commented
So I tried fixing this issue by trying to calculate the angle from which the "observer" looks at the map. Longitude and latitude are just angles projected to 2d panes. If we were able to determine a single 3D angle from the (0,0) axis, knowing from what angle the observer looks at the earth (thanks to rotation values), we could filter which data points should be visible.

The problem with this approach is that when I try to work it out using trigonometry, I end up with a quadratic equation, basically allowing for 2 angles to be a solution (one per "visible" and "hidden" half of the sphere), making my solution worthless. Not sure if my calculations are relevant here, if someone needs them I can try to prepare some notes.

If someone has an idea of how to approach this problem, I would love to pursue this further.

2022-08-24 07:16 UTC, jwoLondon commented
I am not convinced that attempting to filter points based on manual calculation of the projection view is the way to go. As well as the edge cases highlighted above, it makes it rather fragile being dependent on the particular projection used. The more robust general solution is to rely on normal projection clipping where we can (as the original Vega example did).

It should be noted that [pointRadius](https://vega.github.io/vega-lite/docs/projection.html#projection-properties) has been available since VL5 so there are possibilities there. Here, is a [simple example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQOJACckCCGgDaoWRrhoQcNfQCODJAGs4AZRoAvQ0uJJBDQ6gBsSpjVkAJmig-jgMmEbqsmTOIAj+aAAMSsgAHmgAjABMShCYcDhJlBkAviUKegaRbJhI+YmKIH6BwSCh4ZFI0bHx8qj8GQAcyXFI6ahDiWUVIPoIniCqNXVwGY3NQaghsmER6FExjb1o-ACcI2lo52UAukoA7jQB9GgALIkj8DRkWG8fSjglpI4FBMOw+qAlrV8q04KlAUZtFCVslkfkMgpEjcQOUQJgAJ44BZsVT0NhkdQ4GA0KCNHBsfyYABKSACNAYWi2xnhqiMJlJMAs1jsjkM0xAgiQ+LgvNQuhAATqKC5ECpMs8mFUHlxyFUVlaBKJRhibAgMCQRqUADMaIJBEY3DS4Ex3GLyqBFbVWgxVPb0FhcPgiFAArIpBAAnBhMRVJRZHBMAQdgheBR+J6kBAExAAAJZSgAZgIGYI9xJggCAwyiQQ4bkjStJOQe1AhoWmDY9Ok9etJkwPoWUDYDFkmpocC04t1+q5beNcFN5stIBtdqMAGIoFuce6FUrvb6jAG8IQCCGw9JI9HY-HE8nUwIM1nMLn80WS-zzJYbBA6-JrU2dQGoSCzdv+yhLESpL4kYVp9gOk46moM6tiB86LhasRDoIJKwTQqjOqoNL6tatqCAA8ioUB0DBqCJJQWRiLkmpsDYRgukgUAkSAeRLDYADqTwvHRlBiLcJRAA) that allows two-axis rotation and global setting of symbol size. It uses the original geoJSON representation of earthquake sites rather than extracting the long/lat point coordinates.

The problem is that unlike Vega, it is not possible to include data-driven parameterisation in expressions, so using this approach doesn't additionally scale symbols by magnitude.

However, you can encode the magnitude data with other aspects of the point symbolisation including colour. While size encoding doesn't work, strokeWidth does, so it is possible to set a data driven point size while representing earthquake sites as geoJSON. Here is [an example](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQOJACckCCGgDaoWRrhoQcNfQCODJAGs4AZRoAvQ0uJJBDQ6gBsSpjVkAJmig-jgMmEbqsmTOIAj+aAAMSsgAHmgAjMkgEJhwOEmUGQC+xQp6BpFsmEh5iYogfoHBIKHhkUjRsfHyqPwZABzZaZlDpeUg+gieIKrVtXAZDU1BqCGyYRHoUTENPWj8AJzDSOmox6UAukoA7jQB9GgALInZ8DRkWM+vSjhzknAoJh2L1QHMankWnBUn8jNpwQtkgi8hkFIlLiAyiBMABPHAzNiqehsMjqHAwGhQBo4Nj+TAAJSQARoDC0a2MMNURhMRJgFmsdkcogATJisYIkDi4FzULoQAFaih2RBydLPJhVB4schVFYWrj8UYYmwIDAkIalAAzGiCQRGNyUuBMdyGcagBU1FoMVR29BYXD4IhQAKyKQQAJwYTEVSUWRwTAEDYIXgUfgepAQeMQAACwsoAGYCOmCDdCYIAv0sggw3IGpbCcgtqADTNMGwadJa1aTJhvTMoGwGLINTQ4FpxnE1Hr2S2jXATWaLSBrbajABiKCbsUTdNen1Gf14QgEYOh6QRqMxuMJpMpgTpzOYHN5wvFnnmSw2CA1+RWhu1fU8RmTtf2UOZ8SJHEjEtHs+3HLE4FkAdmWiFoB0EQkWmtSNVjA9tpWBMdKGQMgGlndB+WHOhahoUgGmgNxPFALhEBmKVbTYUsdjVIIlHI5ROIaaEaTjYc0HzCdcjmGwsNHcsjD+fCiVHb8SLIoCjEo4EIVo2IGMEJiclgVijHYjCuM6GJVDgXjsQ09AaRuISYTkRCtgkrEpLYGwAHV7kedlsPkhzwIIlTiKQUi+PskAtOo4E6KUfTDO4nRQGEmUQHqMp0s5blTD5T9BScAAqUVikuUptSnOcF3NV1KqAA). It is not perfect because as stroke width is reduced, symbol size tends towards a constant, but perhaps worth considering as an alternative.

And as a cartographic aside, I am personally not convinced of the effectiveness of an orthographic projection for these kinds of data. Why not show [the whole globe at once](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQOJACckCCGgDaoWRrhoQCGrICySMopDEkghodQAGJU1MATNKFM4GmI+qyZIZK+giOIGamNAgMCAAEyGSydAzuIcamaC7GSAAeaAAcShCYcDjZlACMAL41CnoGAWyYSGXWtvaOVYU5brKeqN6yvv7ogcHWJvKo-D05yAWo83UAukoA7jTu9GgAbE458DRkWGgAzIdKOKpsknBQmOwzoLet7UMgcHk3RtpvbTgChcTlWIHqIEwAE8cBE4ABHBh2ACial2EMESChcFUOlA7jaKE+EBw8FUjkwqgcEOQqgA1l5ITCIsE2BAYEhYdYAGY0QSCIx2GhQOBMLrg+r4wmMhiqAXoLC4fBEKDuWRSCDpYTEVSUWRwTAEEYIXgUfgE1oQA0QAACACZKOcCBakAQNmw5e45lUnAgNXIeR7kGNQNCuehMGwcHcZPIlNy4G1ZREoGwGLJKTQ4Fo6kpaQzPmGWXA2RyufG+fKQABiKB1iUNEAuxlkdRPKAMQSOUClco6KpiBQD1a53L0xlFoys9mcjK8-lwQbcuxWkqUth0uAAdW2u2c1TXt03RjFSCgDNzUtaMrlRkVeEIBFV6ukWpoOr1BqNOBNpDNLqtTBbQdJ0XQIRNVHoREkE3CB-TjEBuSDNoJ2ZIxpADa5blhSCoSMBMk3JHMIUpJBZAgJDVAQPEQCgOwO0xD4myTP1WXCSkoUoVMPXcUxAQgbRQWsJAtHQQQ5FoTA0kMSVaPoztASMC04moEt2NUTjuNUXj9DKASqjBJQRKMRjUnScFGzowQGMU9BlL9G4oxxJ5s0oJJhNE3JkjMmTG3nMpcTsli3MsFIpPSeIAD4AF5ElMCwrBqdYvlkVMdKsT5xKCHzGV5OBBEGEAssk6SLKKtocs+PKCpMirwt8kAIBoAAvbtEKzGr0CSMLSqUSd0GgjM6Aq0hrGgOw2v65Q2A2axvmjfUMzQH0lHcNhkCyVBBIUPZkomRxtp9Q4R1HfNUPDWiaFUKAu2sVNxMC9rySYVRhQZCt+QAeRUKA6Dw-c7UHRr12PdBT3PMaQe3XcYEqMQ1hqIA), for example with an equalEarth projection:
<img width="713" alt="globalView" src="https://user-images.githubusercontent.com/1846999/186354529-e5e7beb8-1a8f-4195-9ff7-e63390b3b330.png">

2022-08-29 11:44 UTC, pared commented
Thanks @jwoLondon! I guess i got fixated on filtering. Ill get back to projection.