fix: Add prefix to names in a layer
vega/vega-lite pull request #8663
Opened 2023-01-22 13:16 UTC by ChristopherDavisUCI

This is an attempt to resolve the issues @mattijn raised in #8348 and #8446.  (I believe this PR is independent from my other recent PR, #8662.)

I'm very happy to hear comments:
* Is this approach, making sure there are no duplicate names, the correct approach?
* Is this the right place to make the change?
* Is this a reasonable name format (probably not): `params.repeaterPrefix + spec.name`
* Is there a more natural way to write this logic in JavaScript? 
```
name: spec.name && params.repeaterPrefix ? params.repeaterPrefix + spec.name : undefined
```

A test is currently failing because of this line:
https://github.com/vega/vega-lite/blob/4556109808e023eb2e53507d46c1792725e382b4/test/normalize/toplevelselection.test.ts#L89
Is it correct to have both `normalized.concat[0].layer[0].name` and `normalized.concat[1].layer[0].name` equal to `"a"`?  This PR would change that, so it would break this test.

Thanks again for any comments!

2023-02-20 12:54 UTC, ChristopherDavisUCI commented
Hi @domoritz, thanks for the reviews of my other PRs.  I changed this one to "ready for review" also, although please see my many questions in the [original comment](https://github.com/vega/vega-lite/pull/8663#issue-1552112691) above.

2023-02-20 15:42 UTC, domoritz requested changes

2023-02-20 15:42 UTC, domoritz commented on src/normalize/core.ts
> +      name: spec.name && params.repeaterPrefix ? params.repeaterPrefix + spec.name : undefined,
This will remove the name when there is no repeater prefix, which is definitely wrong (see changed example in this diff).

2023-02-21 14:07 UTC, ChristopherDavisUCI commented
Thanks @domoritz for proposing the fix in #8733!  I will close this, but please let me know if I misunderstood anything.

2023-02-21 14:07 UTC, closed without merging