fix: avoid repetitive labels for integer/year/yearmonth axes
vega/vega-lite pull request #8868
Opened 2023-04-27 21:43 UTC by kanitw

Please:

- [ ] Make the pull requests (PRs) atomic (fix one issue at a time). Multiple relevant issues that must be fixed together? Make atomic commits so we can easily review each issue.
- [ ] Provide a concise title as a [semantic commit message](https://www.conventionalcommits.org/) (e.g. "fix: correctly handle undefined properties") so we can easily copy it to the release note.
  - Use imperative mood and present tense.
- Mention relevant issues in the description (e.g., `Fixes #1` / `Fixes part of #1`).
- [ ] Lint and test (Run `yarn test`).
- [ ] Review your changes before sending the PR (to ensure code quality).
- For new features:
  - [ ] Add new unit tests.
  - [ ] Update the documentation under `site/docs/` + add examples.

Tips:

- https://medium.com/@greenberg/writing-pull-requests-your-coworkers-might-enjoy-reading-9d0307e93da3 is a nice article about writing a nice PR.
- Use draft PR for work in progress PRs / when you want early feedback (https://github.blog/2019-02-14-introducing-draft-pull-requests/).

2023-04-27 22:36 UTC, fandu-db commented on src/compile/axis/properties.ts
> +        }
nit: Since we are doing this for `month`, why not also do it for `quarter`?

2023-04-27 22:37 UTC, fandu-db approved these changes
LGTM. Two nit comments

1. About `quarter`
2. The new behavior seems not captured in any of the test PNGs

2023-04-28 07:55 UTC, domoritz requested changes
This feels complicated. We should instead use tickMinStep as suggested in https://github.com/vega/vega/issues/1503. Ideally this was fixed at the Vega level.

2023-04-28 15:35 UTC, kanitw commented
>  We should instead use tickMinStep as suggested in https://github.com/vega/vega/issues/1503.

Tick min step doesn't really work for time binned axis.  So I'm not sure if it's worth the complexity to implement the solution twice. 

See this [spec](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEzjQATjRyZ289AHE2bMoLgByCAAIImNlADWlnJqhxLTOJgDucOLMsATAAMQQBs-MFBAOyUiipImCiooAzqgmjxiZy2DhCUUBDEIAC+SpjqSLIQAGZs6ghoANqg1TSCmHDqGcoJDAiUEACeCExsggC8k2b6APIz+mYlCi1tHV3JIK1wgsrdCXBxOghwAKqydBmDcEhdShWyZAeojZGhCpFRALrFxZ9KyOp7BlhLIDko-FA2MoaA80KAAB5wzY0ba7dA9DqHGjHM4XdBXG6HQY4J4gDoIHB1JDpJRIeE0CBInQOACyMIAyh0cEi4PDnBkjnAABQYzzY4WRACMAEppZZ+JZBSL9krIkFZSUfkpBkikGQyOo+Jj0EhSBVHnEtjsMs4aK4iSSMgBHBiVHSJHSkTXFIA).


> Ideally this was fixed at the Vega level.

Conceptually, I agree.  But practically, until that happen (which I don't have time for and unlikely that someone gonna fix soon), I don't think we should block this PR on that.

2023-04-28 15:37 UTC, kanitw commented
> The new behavior seems not captured in any of the test PNGs

It does -- see all the SVG changes in the 4th commit:

<img width="542" alt="image" src="https://user-images.githubusercontent.com/111269/235191797-1782b922-4c66-4771-8e7f-e9113aa31e20.png">

Note that some Vega spec may have diffs, but have no visual change since the cap rule still return the original default value.

2023-04-28 21:54 UTC, kanitw commented
Replaced with https://github.com/vega/vega-lite/pull/8872

2023-04-28 21:54 UTC, closed without merging