fix: facet fails on geoshape
vega/vega-lite pull request #9292
Opened 2024-03-24 07:42 UTC by ChiaLingWeng

This will close #3729.

Through this fix can solve current problem, I'm not sure if this is where the issue lies.
Let me know if there's any suggestion.

2024-03-24 15:02 UTC, joelostblom commented
Exciting! Thank you @ChiaLingWeng ! I added an example showing how this works with the code from #3729 (even if that case is more suitable to be used with `repeat` I think it still illustrates that geo faceting now works).

Let's wait for someone else to have a chance to review the code.

2024-03-26 21:12 UTC, domoritz commented
Thanks for the pull request. The fix looks a bit brittle to me as it assumes that the data in the component has a particular order. I don't think I want to merge this without a deeper analysis of the issue and why the fix is correct. Could you look a bit deeper into it?

2024-03-26 21:12 UTC, domoritz requested changes
Thanks for the pull request. The fix looks a bit brittle to me as it assumes that the data in the component has a particular order. I don't think I want to merge this without a deeper analysis of the issue and why the fix is correct. Could you look a bit deeper into it?

2024-07-28 18:01 UTC, domoritz commented
@ChiaLingWeng can you wrap up this pull request?

2024-09-05 05:21 UTC, ChiaLingWeng commented
Hi @domoritz, I'll try to close this, but feel free if you want to take it or provide any suggestion!

2024-09-05 15:09 UTC, domoritz commented
Thanks for working on wrapping this up. Can you try to make the tests run on your fork?

2025-04-20 02:43 UTC, domoritz commented
The fix is too brittle so it needs more work. Please make a new pull request.

2025-04-20 02:43 UTC, closed without merging